version: '3.7'

services:
  hive:
    image: loum/acrta-hive:latest
    build:
      context: ./docker/hive
    container_name: hive
    volumes:
      - ./data:/data
      - ./schemas:/schemas
      - ./scripts:/scripts
    ports:
      - 10000:10000

  zeppelin:
    image: loum/zeppelin-hive:latest
    build:
      context: docker/zeppelin-hive
    container_name: zeppelin
    environment:
      ZEPPELIN_LOG_DIR: /logs
      ZEPPELIN_NOTEBOOK_DIR: /notebook
      ZEPPELIN_ADDR: 0.0.0.0
    volumes:
      - ./docker/zeppelin-hive/notebook:/notebook
      - ./logs:/logs
    ports:
      - 8080:8080
