version: '3.7'

services:
  hive:
    image: loum/hive-on-spark:3.1.2-2.4.8-1
    container_name: hive
    volumes:
      - ./data:/data
      - ./schemas:/schemas
      - ./scripts:/scripts
    ports:
      - 10000:10000
      - 10002:10002
      - 8032:8032
      - 8088:8088
      - 8042:8042
      - 18080:18080

  zeppelin:
    image: loum/zeppelin-hive:0.9.0-3.1.2-1
    container_name: zeppelin
    environment:
      ZEPPELIN_PORT: 18888
      ZEPPELIN_NOTEBOOK_DIR: /home/zeppelin/zeppelin/notebook
      ZEPPELIN_ADDR: 0.0.0.0
      ZEPPELIN_INTERPRETER_DEP_MVNREPO: https://repo1.maven.org/maven2/
      ZEPPELIN_INTERPRETER_HIVE_DEFAULT_URL: jdbc:hive2://hive:10000
    volumes:
      - ./zeppelin/notebook:/home/zeppelin/zeppelin/notebook
    ports:
      - 18888:18888
